import { lazy } from 'react';
import type { WidgetType, WidgetRegistryEntry } from '@/types';

export const widgetRegistry: Record<WidgetType, WidgetRegistryEntry> = {
  /* ====== FREE widgets (sorted by common usage) ====== */

  clock: {
    type: 'clock',
    displayName: 'Clock',
    description: 'Digital or analog clock with multiple styles',
    tier: 'free',
    icon: '\u{1F552}',
    component: lazy(() => import('@/components/widgets/ClockWidget')),
    defaultConfig: { style: 'minimal-digital', format: '12h', showSeconds: true },
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 2, h: 2 },
  },
  weather: {
    type: 'weather',
    displayName: 'Weather',
    description: 'Current conditions and forecast via Open-Meteo',
    tier: 'free',
    icon: '\u{26C5}',
    component: lazy(() => import('@/components/widgets/WeatherWidget')),
    defaultConfig: { latitude: 40.7128, longitude: -74.006, units: 'fahrenheit', pollInterval: 900000 },
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 2 },
  },
  calendar: {
    type: 'calendar',
    displayName: 'Calendar',
    description: 'Month view or Google Calendar embed',
    tier: 'free',
    icon: '\u{1F4C6}',
    component: lazy(() => import('@/components/widgets/CalendarWidget')),
    defaultConfig: { source: 'built-in' },
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 3, h: 2 },
    maxIframes: 1,
  },
  date: {
    type: 'date',
    displayName: 'Date',
    description: 'Current date with day of week',
    tier: 'free',
    icon: '\u{1F4C5}',
    component: lazy(() => import('@/components/widgets/DateWidget')),
    defaultConfig: { format: 'long' },
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 2, h: 1 },
  },
  countdown: {
    type: 'countdown',
    displayName: 'Countdown',
    description: 'Timer counting down to a target date',
    tier: 'free',
    icon: '\u{23F3}',
    component: lazy(() => import('@/components/widgets/CountdownWidget')),
    defaultConfig: { targetDate: '', label: 'Countdown' },
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 2, h: 2 },
  },
  'alarm-clock': {
    type: 'alarm-clock',
    displayName: 'Alarm Clock',
    description: 'Set alarms with audible notifications',
    tier: 'free',
    icon: '\u{23F0}',
    component: lazy(() => import('@/components/widgets/AlarmClockWidget')),
    defaultConfig: { alarmTime: '07:00', enabled: false, sound: 'classic', label: 'Wake Up' },
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
  },
  quote: {
    type: 'quote',
    displayName: 'Quote',
    description: 'Inspirational quote display',
    tier: 'free',
    icon: '\u{1F4AC}',
    component: lazy(() => import('@/components/widgets/QuoteWidget')),
    defaultConfig: { category: 'inspirational', refreshInterval: 3600000 },
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 2 },
  },
  'eth-usage': {
    type: 'eth-usage',
    displayName: 'Network Traffic',
    description: 'Network throughput and request monitoring',
    tier: 'free',
    icon: '\u{1F310}',
    component: lazy(() => import('@/components/widgets/EthUsageWidget')),
    defaultConfig: { pollInterval: 3000, resetOnSwitch: false },
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 2 },
  },

  /* ====== PREMIUM widgets (sorted by common usage) ====== */

  youtube: {
    type: 'youtube',
    displayName: 'YouTube',
    description: 'Embed YouTube videos',
    tier: 'premium',
    icon: '\u{25B6}\u{FE0F}',
    component: lazy(() => import('@/components/widgets/YouTubeWidget')),
    defaultConfig: { videoUrl: '', autoplay: false, loop: false },
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 3, h: 2 },
    maxIframes: 1,
  },
  music: {
    type: 'music',
    displayName: 'Music',
    description: 'Spotify embed player',
    tier: 'premium',
    icon: '\u{1F3B5}',
    component: lazy(() => import('@/components/widgets/MusicWidget')),
    defaultConfig: { spotifyUrl: '', theme: 'dark' },
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 2 },
    maxIframes: 1,
  },
  stocks: {
    type: 'stocks',
    displayName: 'Stocks',
    description: 'TradingView stock/crypto charts',
    tier: 'premium',
    icon: '\u{1F4C8}',
    component: lazy(() => import('@/components/widgets/StocksWidget')),
    defaultConfig: { symbols: ['AAPL', 'GOOGL'], chartType: 'mini', pollInterval: 60000 },
    defaultSize: { w: 8, h: 2 },
    minSize: { w: 4, h: 2 },
    maxIframes: 1,
  },
  pomodoro: {
    type: 'pomodoro',
    displayName: 'Pomodoro',
    description: 'Focus timer with work/break cycles',
    tier: 'premium',
    icon: '\u{1F345}',
    component: lazy(() => import('@/components/widgets/PomodoroWidget')),
    defaultConfig: { workMinutes: 25, breakMinutes: 5, longBreakMinutes: 15, sessionsBeforeLongBreak: 4 },
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 3, h: 2 },
  },
  'photo-frame': {
    type: 'photo-frame',
    displayName: 'Photo Frame',
    description: 'Rotating photo slideshow',
    tier: 'premium',
    icon: '\u{1F5BC}\u{FE0F}',
    component: lazy(() => import('@/components/widgets/PhotoFrameWidget')),
    defaultConfig: { photos: [], interval: 10000, transition: 'fade' },
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 3, h: 2 },
  },
  'cpu-usage': {
    type: 'cpu-usage',
    displayName: 'CPU Usage',
    description: 'Estimated CPU utilization and core count',
    tier: 'premium',
    icon: '\u{1F9E0}',
    component: lazy(() => import('@/components/widgets/CPUUsageWidget')),
    defaultConfig: { pollInterval: 2000, displayMode: 'gauge' },
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 2 },
  },
  'memory-usage': {
    type: 'memory-usage',
    displayName: 'Memory Usage',
    description: 'JavaScript heap memory usage (Chrome)',
    tier: 'premium',
    icon: '\u{1F4BE}',
    component: lazy(() => import('@/components/widgets/MemoryUsageWidget')),
    defaultConfig: { pollInterval: 3000 },
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 2 },
  },
};

export function getRegistryEntry(type: WidgetType): WidgetRegistryEntry {
  return widgetRegistry[type];
}

export function getWidgetsByTier(tier: 'free' | 'premium'): WidgetRegistryEntry[] {
  return Object.values(widgetRegistry).filter((w) => w.tier === tier);
}
